# Generated by Django 4.2.8 on 2023-12-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=20)),
                ('adr', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity_per', models.FloatField()),
                ('pcs_fts', models.FloatField()),
                ('rate', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('hsn_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('Cname', models.CharField(max_length=20)),
                ('Pname', models.CharField(max_length=20)),
                ('Dname', models.CharField(max_length=20)),
                ('Lno', models.CharField(max_length=20)),
                ('pcno', models.CharField(max_length=20)),
                ('scno', models.CharField(max_length=20)),
                ('pcs', models.FloatField()),
                ('trip', models.FloatField()),
                ('df1', models.DateField(blank=True, null=True)),
                ('df2', models.DateField(blank=True, null=True)),
                ('df3', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.product')),
            ],
        ),
    ]
