# Generated by Django 4.2.8 on 2023-12-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_orders_amount_orders_height_orders_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
