# Generated by Django 4.2.8 on 2023-12-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_remove_orders_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=20)),
                ('bill_date', models.DateField()),
                ('final_rate', models.FloatField()),
                ('material_rate', models.FloatField()),
                ('transport_rate', models.FloatField()),
                ('final_amount', models.FloatField()),
                ('mcode', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], max_length=20)),
                ('tcode', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2')], max_length=20)),
                ('billed', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='billed',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
