# Generated by Django 4.2.8 on 2024-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_alter_billing_bill_date_alter_billing_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='oid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='place',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='product',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
