# Generated by Django 4.2.8 on 2024-01-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_billing_oid_billing_place_billing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pcs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
