# Generated by Django 4.2.9 on 2024-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_alter_orders_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='AggregatedAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='AggregatedQuantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
