# Generated by Django 4.2.9 on 2024-01-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_orders_aggregatedamount_orders_aggregatedquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mergedOids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
