# Generated by Django 4.2.9 on 2024-01-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_orders_mergedoids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('lorry_no', models.CharField(max_length=20)),
                ('trip', models.FloatField()),
                ('challan', models.CharField(max_length=20)),
                ('hsn', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('aggregated_quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('aggregated_amount', models.FloatField()),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('final_amount', models.FloatField()),
            ],
        ),
    ]
