# Generated by Django 4.2.9 on 2024-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0015_record_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
