# Generated by Django 4.2.9 on 2024-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0016_record_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='InvoiceEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
