# Generated by Django 4.2.9 on 2024-01-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0017_record_invoiceend_record_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
